export const POSTS = [
    { 
        date: "JUNE 2024", 
        title: "The weirdest vector algebra class", 
        slug: "the-weirdest-vector-algebra-class",
        href: "/blog/the-weirdest-vector-algebra-class", 
        excerpt: "Reflecting on an unexpected lesson in vector algebra.",
        image: "/hero-character-removebg-preview.png",
        caption: "A lesson in direction and magnitude.",
    },
    { 
        date: "MARCH 2024", 
        title: "The day it rained", 
        slug: "the-day-it-rained",
        href: "/blog/the-day-it-rained", 
        excerpt: "A story about rain and its impact.",
        image: "/hero-character-removebg-preview.png",
        caption: "Watching the world wash away.",
    },
    { 
        date: "MARCH 2024", 
        title: "The Green Eyed Monster", 
        slug: "the-green-eyed-monster",
        href: "/blog/the-green-eyed-monster", 
        excerpt: "Thoughts on jealousy and human nature.",
        image: "/hero-character-removebg-preview.png",
        caption: "Reflections in the mirror.",
    },
    { 
        date: "MARCH 2024", 
        title: "Comfort zone", 
        slug: "comfort-zone",
        href: "/blog/comfort-zone", 
        excerpt: "Why stepping out of your comfort zone is essential.",
        image: "/hero-character-removebg-preview.png",
        caption: "Breaking through the wall.",
    },
];
